### ISSUE TITLE
Error during import with abapGit

### ISSUE THREAD

**Issue by se38** [abapkochbuch/Sources#1]
During the import of the offline .zip with abapGit (1.69.1) I'm getting the error "Error from RS_FUNCTION_POOL_CONTENTS"
I'm using the ABAP Developer Edition 7.51 SP02

Any idea?

Cheers, Uwe (aka @se38)

**Comment by larshp** [comment]
try syntax checking the function groups

**Comment by se38** [comment]
The function groups (and everything else from the .zip) aren't there yet, so they are empty and the function RS_FUNCTION_POOL_CONTENTS is returning a subrc = 1.

**Comment by larshp** [comment]
First part regarding RS_FUNCTION_POOL_CONTENTS is fixed in latest abapGit version

Next error is when inserting a dynpro, due to non-activated DDIC objects. Eg. the following table uses data elements ERZET and AEZET which does not exist in ABAP Developer Edition 7.51 SP02.
abapGit does not show an error after trying to activate the DDIC, I will investigate

![image](https://user-images.githubusercontent.com/5888506/42034638-f418bd9a-7ae0-11e8-9e4f-23452209027d.png)

**Comment by larshp** [comment]
Full error list, some of these errors are due to abapGit, other because the referenced objects does not exist:


Konvertierungsroutine ZBPER existiert nicht
Domäne ZBOOK_LOCATION ist nicht aktiv vorhanden
Parameter-Id ZBOOK_TICKET_NR ist nicht in der Tabelle TPARA enthalten
INCLUDE-Tabelle VBAK ist nicht aktiv vorhanden
INCLUDE-Tabelle VBAK ist nicht aktiv vorhanden
Routine EXPAND (Tabelle ZBOOK_DEMO_VBAK konnte nicht expandiert werden)
Feld TEXT: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Nametab zu Tabelle ZBOOK_TEAM kann nicht generiert werden
Domäne ZBOOK_PERSON ist nicht aktiv vorhanden
Domäne ZBOOK_PERSON ist nicht aktiv vorhanden
Feld AETIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Nametab zu Tabelle ZBOOK_AREAS kann nicht generiert werden
Feld AETIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld ERTIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld LOCATION: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld OWNER: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld RESPONSIBLE: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld TIKNR: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld R_LOG: Verwendeter Referenztyp ZCL_BOOK_TICKET_LOG ist nicht aktiv
Nametab zu Tabelle ZBOOK_TICKET_OVERVIEW kann nicht generiert werden
Feld SO_CLAS: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld SO_RESP: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld SO_STAT: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld SO_TIKNR: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Nametab zu Tabelle ZBOOK_TICKET_SO_RANGES kann nicht generiert werden
Suchfeld ZBOOK_CLASS-CLAS der Suchhilfeanbindung: Suchhilfe ZBOOK_CLAS ist nicht aktiv
Feld CTEXT: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Nametab zu Tabelle ZBOOK_CLAST kann nicht generiert werden
Tabelle ZBOOK_CLASS ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Suchfeld ZBOOK_CLASS-CLAS der Suchhilfeanbindung: Suchhilfe ZBOOK_CLAS ist nicht aktiv
Tabelle ZBOOK_CLASS ist nicht aktiv vorhanden oder inkonsistent
Schlüsselfeld TIKNR hat den unerlaubten Typ
Feld AETIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld ERTIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld LOCATION: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld OWNER: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld RESPONSIBLE: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld TIKNR: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld TIKNR nicht als Schlüsselfeld verwendbar, da kein Default für Typ   ex.
Suchfeld ZBOOK_TICKET-TIKNR der Suchhilfeanbindung: Suchhilfe ZBOOK_TICKET ist nicht aktiv
Nametab zu Tabelle ZBOOK_TICKET kann nicht generiert werden
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Schlüsselfeld TIKNR hat den unerlaubten Typ
Feld AETIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld ERTIM: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld LOCATION: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld OWNER: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld RESPONSIBLE: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld TIKNR: Komponententyp o. benutzte Domäne nicht aktiv o. nicht vorhanden
Feld TIKNR nicht als Schlüsselfeld verwendbar, da kein Default für Typ   ex.
Suchfeld ZBOOK_TICKET-TIKNR der Suchhilfeanbindung: Suchhilfe ZBOOK_TICKET ist nicht aktiv
Nametab zu Tabelle ZBOOK_TICKET kann nicht generiert werden
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Der als Suchhilfe-Exit angegebene Funktionsbaustein Z_BOOK_TICKET_SHLP_EXIT ist nicht vorhanden
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
Tabelle ZBOOK_TICKET ist keine Datenbanktabelle => als Selektionsmethode ungeeignet
INCLUDE-Tabelle ZBOOK_TICKET ist nicht aktiv vorhanden
INCLUDE-Tabelle ZBOOK_AREAV ist nicht aktiv vorhanden
INCLUDE-Tabelle ZBOOK_CLASV ist nicht aktiv vorhanden
Routine EXPAND (Tabelle ZBOOK_TICKET_DYNPRO konnte nicht expandiert werden)
Typ ZBOOK_TICKET zu Komponente HEAD ist nicht aktiv vorhanden
Routine EXPAND (Tabelle ZBOOK_TICKET_OUTPUT konnte nicht expandiert werden)
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA nicht existentem Suchhilfeparameter ZBOOK_TICKET-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS nicht existentem Suchhilfeparameter ZBOOK_TICKET-CLAS zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter ZBOOK_TICKET-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA nicht existentem Suchhilfeparameter ZBOOK_TICKET_DUE-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS nicht existentem Suchhilfeparameter ZBOOK_TICKET_DUE-CLAS zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter ZBOOK_TICKET_DUE-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA nicht existentem Suchhilfeparameter ZBOOK_TICKET_STATUS-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS nicht existentem Suchhilfeparameter ZBOOK_TICKET_STATUS-CLAS zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter ZBOOK_TICKET_STATUS-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA nicht existentem Suchhilfeparameter ZBOOK_TICKET_OPEN-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS nicht existentem Suchhilfeparameter ZBOOK_TICKET_OPEN-CLAS zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter ZBOOK_TICKET_OPEN-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA nicht existentem Suchhilfeparameter ZBOOK_TICKET_WORK-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS nicht existentem Suchhilfeparameter ZBOOK_TICKET_WORK-CLAS zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter ZBOOK_TICKET_WORK-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA nicht existentem Suchhilfeparameter ZBOOK_TICKET_HOLD-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS nicht existentem Suchhilfeparameter ZBOOK_TICKET_HOLD-CLAS zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter ZBOOK_TICKET_HOLD-TIKNR zugeordnet
Suchhilfe ZBOOK_TICKET_COLL inkludiert nicht aktive Suchhilfe ZBOOK_TICKET
Suchhilfe ZBOOK_TICKET_COLL inkludiert nicht aktive Suchhilfe ZBOOK_TICKET_DUE
Suchhilfe ZBOOK_TICKET_COLL inkludiert nicht aktive Suchhilfe ZBOOK_TICKET_HOLD
Suchhilfe ZBOOK_TICKET_COLL inkludiert nicht aktive Suchhilfe ZBOOK_TICKET_OPEN
Suchhilfe ZBOOK_TICKET_COLL inkludiert nicht aktive Suchhilfe ZBOOK_TICKET_STATUS
Suchhilfe ZBOOK_TICKET_COLL inkludiert nicht aktive Suchhilfe ZBOOK_TICKET_WORK
Domäne ZBOOK_PERSON konnte nicht aktiviert werden
Datenelement ZBOOK_LOCATION konnte nicht aktiviert werden
Datenelement ZBOOK_PERSON_OWNER konnte nicht aktiviert werden
Datenelement ZBOOK_PERSON_REPSONSIBLE konnte nicht aktiviert werden
Datenelement ZBOOK_TICKET_NR konnte nicht aktiviert werden
Suchhilfe ZBOOK_CLAS konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_COLL konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_DUE konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_EXIT konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_HOLD konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_OPEN konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_PARAM konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_STATUS konnte nicht aktiviert werden
Suchhilfe ZBOOK_TICKET_WORK konnte nicht aktiviert werden
Tabelle ZBOOK_AREAS konnte nicht aktiviert werden
Tabelle ZBOOK_CLASS konnte nicht aktiviert werden
Tabelle ZBOOK_CLAST konnte nicht aktiviert werden
Tabelle ZBOOK_DEMO_VBAK konnte nicht aktiviert werden
Tabelle ZBOOK_TEAM konnte nicht aktiviert werden
Tabelle ZBOOK_TICKET konnte nicht aktiviert werden
Tabelle ZBOOK_TICKET_DYNPRO konnte nicht aktiviert werden
Tabelle ZBOOK_TICKET_OUTPUT konnte nicht aktiviert werden
Tabelle ZBOOK_TICKET_OVERVIEW konnte nicht aktiviert werden
Tabelle ZBOOK_TICKET_SO_RANGES konnte nicht aktiviert werden
View ZBOOK_CLASV konnte nicht aktiviert werden
Returncode...............: 8

**Comment by se38** [comment]
Oh, looks like you need a full ERP system to use the sample code. Should be mentioned in the Wiki.
@tricktresor : are you watching?

Regarding the RS_FUNCTION_POOL_CONTENTS problem: I'm trying to import the source into another system (ERP 7.50) with the newest abapGit tomorrow. Will report back.

**Comment by abapkochbuch** [comment]
I will check missing elements and add them. (Conversion exit is missing indeed).
Also we tried to make the code "mini sap compatible". Seems that this didn't work out well... :(

**Comment by abapkochbuch** [comment]
@se38 could you please check which alternatives are available in ABAP Developer Edition 7.51 SP02 for

- ERDAT
- ERZET
- ERNAM
- AEDAT
- AEZET

thanks!

Just used SYDATUM and SYUZEIT instead.

**Comment by abapkochbuch** [comment]
Just corrected missing elements and replaced ERP elements to elements hopefully existing in Developer Edition.

**Comment by larshp** [comment]
looks like domain ZBOOK_LOCATION and domain ZBOOK_PERSON is missing in the repo

plus standard data element BEZEI_40 and data element AETIM does not exist in 751 dev edition

**Comment by abapkochbuch** [comment]
ZBOOK_PERSON should be in the repo. 
ZBOOK_LOCATION added.
Also exchanged BEZEI_40 with TEXT40.
AETIM also xchanged by SYUZEIT

**Comment by se38** [comment]
We are coming closer :-)

Next I'm getting a "RPY_DYNPRO_INSERT" error (illegal_field_value) with dynpro
PROGRAM SAPMZBOOK_TICKET
SCREEN 0050

(abapGit 1.70.0, ABAP Developer edition)

**Comment by abapkochbuch** [comment]
hmm... there is just a frame and the input field ZBOOK_TICKET_DYNPRO-TIKNRTIK
there is nothing special and no elements that should be missing... :/

I removed the frame... Maybe you would like to try again.
Otherwise it would be nice if you could find out the exact position of RAISE ILLEGAL_FIELD_VALUE.

**Comment by se38** [comment]
Found it with debugging:
"Tabelle ZBOOK_TICKET_DYNPRO ist im Data Dictionary nicht aktiv vorhanden"

**Comment by abapkochbuch** [comment]
Isn't it? Could you please check if it's may be only _inactive_?

**Comment by se38** [comment]
Ah, true. And that's because (at least) the conversationroutine ZBPER for domain ZBOOK_PERSON could not be found. 
I hope all the other errors in the activation log are follow errors.

---------- mass activation log -------
DOMA ZBOOK_PERSON   wurde nicht aktiviert
--
PrÃ¼fe DomÃ¤ne ZBOOK_PERSON   (DEVELOPER/29.06.18/11:59)
Konvertierungsroutine ZBPER existiert   nicht
DomÃ¤ne ZBOOK_PERSON ist inkonsistent
DTEL ZBOOK_AREA wurde aktiviert
DTEL ZBOOK_CLAS wurde aktiviert
DTEL ZBOOK_ICON_CHANGE wurde aktiviert
DTEL ZBOOK_LOCATION wurde aktiviert
DTEL ZBOOK_TICKET_NR wurde nicht   aktiviert
PrÃ¼fe Datenelement ZBOOK_TICKET_NR   (DEVELOPER/29.06.18/11:59)
Parameter-Id ZBOOK_TICKET_NR ist nicht in   der Tabelle TPARA enthalten
Suchhilfe ZBOOK_TICKET_COLL ist nicht   aktiv oder besitzt keine Parameter
Datenelement ZBOOK_TICKET_NR ist   inkonsistent
DTEL ZBOOK_TICKET_STATUS wurde aktiviert
TABL ZBOOK_TEAM wurde nicht aktiviert
PrÃ¼fe Tabelle ZBOOK_TEAM   (DEVELOPER/29.06.18/11:59)
 
 
Feld TEXT: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Nametab zu Tabelle ZBOOK_TEAM kann nicht   generiert werden
PrÃ¼fen der Tabelle ZBOOK_TEAM lieferte   Fehler
DTEL ZBOOK_PERSON_OWNER wurde nicht   aktiviert
PrÃ¼fe Datenelement ZBOOK_PERSON_OWNER   (DEVELOPER/29.06.18/11:59)
DomÃ¤ne ZBOOK_PERSON ist nicht aktiv   vorhanden
Datenelement ZBOOK_PERSON_OWNER ist   inkonsistent
DTEL ZBOOK_PERSON_REPSONSIBLE wurde nicht   aktiviert
PrÃ¼fe Datenelement   ZBOOK_PERSON_REPSONSIBLE (DEVELOPER/29.06.18/11:59
DomÃ¤ne ZBOOK_PERSON ist nicht aktiv   vorhanden
Datenelement ZBOOK_PERSON_REPSONSIBLE ist   inkonsistent
TABL ZBOOK_TICKET_OVERVIEW wurde nicht   aktiviert
PrÃ¼fe Tabelle ZBOOK_TICKET_OVERVIEW   (DEVELOPER/29.06.18/11:59)
Feld OWNER: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld RESPONSIBLE: Komponententyp o.   benutzte DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld TIKNR: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld R_LOG: Verwendeter Referenztyp   ZCL_BOOK_TICKET_LOG ist nicht aktiv
Nametab zu Tabelle ZBOOK_TICKET_OVERVIEW   kann nicht generiert werden
PrÃ¼fen der Tabelle ZBOOK_TICKET_OVERVIEW   lieferte Fehler
TTYP ZBOOK_RT_AREA wurde aktiviert
TABL ZBOOK_TICKET_SO_RANGES wurde nicht   aktiviert
PrÃ¼fe Tabelle ZBOOK_TICKET_SO_RANGES   (DEVELOPER/29.06.18/11:59)
 
 
Feld SO_CLAS: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld SO_RESP: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld SO_STAT: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld SO_TIKNR: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Nametab zu Tabelle ZBOOK_TICKET_SO_RANGES   kann nicht generiert werden
PrÃ¼fen der Tabelle   ZBOOK_TICKET_SO_RANGES lieferte Fehler
TABL ZBOOK_CLAST wurde nicht aktiviert
PrÃ¼fe Tabelle ZBOOK_CLAST   (DEVELOPER/29.06.18/11:59)
PrÃ¼ftab. ZBOOK_CLASS exist. nicht bzw.   besitzt keine SchlÃ¼sselfelder
PrÃ¼ftab. ZBOOK_CLASS exist. nicht bzw.   besitzt keine SchlÃ¼sselfelder
 
PrÃ¼fen der Tabelle ZBOOK_CLAST lieferte   Fehler
SHLP ZBOOK_CLAS wurde nicht aktiviert
PrÃ¼fe Suchhilfe ZBOOK_CLAS   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_CLASS ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_CLAS ist inkonsistent
TABL ZBOOK_CLASS wurde nicht aktiviert
PrÃ¼fe Tabelle ZBOOK_CLASS   (DEVELOPER/29.06.18/11:59)
Suchfeld ZBOOK_CLASS-CLAS der   Suchhilfeanbindung: Suchhilfe ZBOOK_CLAS ist nicht aktiv
 
PrÃ¼fen der Tabelle ZBOOK_CLASS lieferte   Fehler
VIEW ZBOOK_CLASV wurde nicht aktiviert
PrÃ¼fe View ZBOOK_CLASV   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_CLASS ist nicht aktiv   vorhanden oder inkonsistent
View ZBOOK_CLASV ist nicht konsistent
SHLP ZBOOK_TICKET wurde nicht aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET ist inkonsistent
TABL ZBOOK_TICKET wurde nicht aktiviert
PrÃ¼fe Tabelle ZBOOK_TICKET   (DEVELOPER/29.06.18/11:59)
SchlÃ¼sselfeld TIKNR hat den unerlaubten   Typ
Feld OWNER: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld RESPONSIBLE: Komponententyp o.   benutzte DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld TIKNR: Komponententyp o. benutzte   DomÃ¤ne nicht aktiv o. nicht vorhanden
Feld TIKNR nicht als SchlÃ¼sselfeld   verwendbar, da kein Default fÃ¼r Typ     ex.
 
 
PrÃ¼ftab. ZBOOK_CLASS exist. nicht bzw.   besitzt keine SchlÃ¼sselfelder
Suchfeld ZBOOK_TICKET-TIKNR der   Suchhilfeanbindung: Suchhilfe ZBOOK_TICKET ist nicht aktiv
Nametab zu Tabelle ZBOOK_TICKET kann   nicht generiert werden
PrÃ¼fen der Tabelle ZBOOK_TICKET lieferte   Fehler
SHLP ZBOOK_TICKET_DUE wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_DUE   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_DUE ist   inkonsistent
SHLP ZBOOK_TICKET_EXIT wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_EXIT   (DEVELOPER/29.06.18/11:59)
Der als Suchhilfe-Exit angegebene   Funktionsbaustein Z_BOOK_TICKET_SHLP_EXIT ist nicht vorhanden
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_EXIT ist   inkonsistent
SHLP ZBOOK_TICKET_HOLD wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_HOLD   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_HOLD ist   inkonsistent
SHLP ZBOOK_TICKET_OPEN wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_OPEN   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_OPEN ist   inkonsistent
SHLP ZBOOK_TICKET_PARAM wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_PARAM   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_PARAM ist   inkonsistent
SHLP ZBOOK_TICKET_STATUS wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_STATUS   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_STATUS ist   inkonsistent
SHLP ZBOOK_TICKET_WORK wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_WORK   (DEVELOPER/29.06.18/11:59)
Tabelle ZBOOK_TICKET ist keine   Datenbanktabelle => als Selektionsmethode ungeeignet
Suchhilfe ZBOOK_TICKET_WORK ist   inkonsistent
TABL ZBOOK_TICKET_DYNPRO wurde nicht   aktiviert
PrÃ¼fe Tabelle ZBOOK_TICKET_DYNPRO   (DEVELOPER/29.06.18/11:59)
INCLUDE-Tabelle ZBOOK_TICKET ist nicht   aktiv vorhanden
INCLUDE-Tabelle ZBOOK_AREAV ist nicht   aktiv vorhanden
INCLUDE-Tabelle ZBOOK_CLASV ist nicht   aktiv vorhanden
Routine EXPAND (Tabelle   ZBOOK_TICKET_DYNPRO konnte nicht expandiert werden)
PrÃ¼fen der Tabelle ZBOOK_TICKET_DYNPRO   lieferte Fehler
TABL ZBOOK_TICKET_OUTPUT wurde nicht   aktiviert
PrÃ¼fe Tabelle ZBOOK_TICKET_OUTPUT   (DEVELOPER/29.06.18/11:59)
Typ ZBOOK_TICKET zu Komponente HEAD ist   nicht aktiv vorhanden
Routine EXPAND (Tabelle   ZBOOK_TICKET_OUTPUT konnte nicht expandiert werden)
PrÃ¼fen der Tabelle ZBOOK_TICKET_OUTPUT   lieferte Fehler
SHLP ZBOOK_TICKET_COLL wurde nicht   aktiviert
PrÃ¼fe Suchhilfe ZBOOK_TICKET_COLL   (DEVELOPER/29.06.18/11:59)
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA   nicht existentem Suchhilfeparameter ZBOOK_TICKET-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS   nicht existentem Suchhilfeparameter ZBOOK_TICKET-CLAS zugeordnet
Suchhilfeparameter   ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter   ZBOOK_TICKET-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA   nicht existentem Suchhilfeparameter ZBOOK_TICKET_DUE-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS   nicht existentem Suchhilfeparameter ZBOOK_TICKET_DUE-CLAS zugeordnet
Suchhilfeparameter   ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter   ZBOOK_TICKET_DUE-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA   nicht existentem Suchhilfeparameter ZBOOK_TICKET_STATUS-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS   nicht existentem Suchhilfeparameter ZBOOK_TICKET_STATUS-CLAS zugeordnet
Suchhilfeparameter   ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter   ZBOOK_TICKET_STATUS-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA   nicht existentem Suchhilfeparameter ZBOOK_TICKET_OPEN-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS   nicht existentem Suchhilfeparameter ZBOOK_TICKET_OPEN-CLAS zugeordnet
Suchhilfeparameter   ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter   ZBOOK_TICKET_OPEN-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA   nicht existentem Suchhilfeparameter ZBOOK_TICKET_WORK-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS   nicht existentem Suchhilfeparameter ZBOOK_TICKET_WORK-CLAS zugeordnet
Suchhilfeparameter   ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter   ZBOOK_TICKET_WORK-TIKNR zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-AREA   nicht existentem Suchhilfeparameter ZBOOK_TICKET_HOLD-AREA zugeordnet
Suchhilfeparameter ZBOOK_TICKET_COLL-CLAS   nicht existentem Suchhilfeparameter ZBOOK_TICKET_HOLD-CLAS zugeordnet
Suchhilfeparameter   ZBOOK_TICKET_COLL-TIKNR nicht existentem Suchhilfeparameter   ZBOOK_TICKET_HOLD-TIKNR zugeordnet
Suchhilfe ZBOOK_TICKET_COLL inkludiert   nicht aktive Suchhilfe ZBOOK_TICKET
Suchhilfe ZBOOK_TICKET_COLL inkludiert   nicht aktive Suchhilfe ZBOOK_TICKET_DUE
Suchhilfe ZBOOK_TICKET_COLL inkludiert   nicht aktive Suchhilfe ZBOOK_TICKET_HOLD
Suchhilfe ZBOOK_TICKET_COLL inkludiert   nicht aktive Suchhilfe ZBOOK_TICKET_OPEN
Suchhilfe ZBOOK_TICKET_COLL inkludiert   nicht aktive Suchhilfe ZBOOK_TICKET_STATUS
Suchhilfe ZBOOK_TICKET_COLL inkludiert   nicht aktive Suchhilfe ZBOOK_TICKET_WORK
Suchhilfe ZBOOK_TICKET_COLL ist   inkonsistent

**Comment by tricktresor** [comment]
Conversation Routine 🥇 😆 
The conversion routine only exists implicitly in the way that there are the two function modules CONVERSION_EXIT_xxxxx_INPUT and _OUTPUT.
These modules are in the repository...
I don't know if there is any additional table entry that must be set... I would swear not, but... 🤷‍♂️

**Comment by se38** [comment]
Grr, damned autocorrect (no it was just in my head) ;-)
But the function modules aren't there either. 

@larshp : maybe we have a problem with the import order here -> Domain with conversion exit = these function modules have to be imported first. Could we identify them via name in abapGit? Tricky situation. Should I open an issue in abapGit?

**Comment by tricktresor** [comment]
The conversion exit function modules  really were not in the package although I changed the package. 
But *NOW* they're in!
Hopefully... ;)

**Comment by se38** [comment]
Still the same problem because the domain could not be activated before the function modules are present. And Dynpros can't be imported before the tables/structures are active. But I think this is an abapGit problem and not yours.

**Comment by tricktresor** [comment]
And activating manually?

I could temporarily remove the conversion exit from the domain.

**Comment by se38** [comment]
Activating manually what? 
The domain can't be activated without the function modules and the function modules aren't imported yet because the import of the dynpro failed because the structures/tables aren't active yet because the domain isn't active yet because... (oops, loop)
I think we have to wait for @larshp . Maybe he has an idea.

(or I'm totally wrong and the problem is somewhere else...)

**Comment by tricktresor** [comment]
I removed the conversion exit.
Activation should be possible now.

**Comment by se38** [comment]
Domain could be activated now.
Further errors I'll communicate via mail. Don't want to pollute this ticket with mass activation logs ;-)

**Comment by larshp** [comment]
yeah, abapGit saves/activates all DDIC before the code, which is a problem for conversion exits, hmm

**Comment by larshp** [comment]
With https://github.com/larshp/abapGit/pull/1572 we are one step further,

![image](https://user-images.githubusercontent.com/5888506/42382652-482921cc-8135-11e8-8493-d675932e4fda.png)
looks like 

- ZBOOK_RT_CLAS
- ZBOOK_RT_PERSON_REPSONSIBLE
- ZBOOK_RT_TICKET_NR
- ZBOOK_RT_STATUS

are missing in the repo

![image](https://user-images.githubusercontent.com/5888506/42382824-b9b97bfc-8135-11e8-93b6-d1f7aced5971.png)
Data element SORTN not found

**Comment by tricktresor** [comment]
Great! Thanks, Lars! 
I added the missing elementes and hope that NUMC04 (instfead of SORTN) is available in developer edition...

**Comment by larshp** [comment]
cool, I will test again sometime, probably during the weekend. I guess there are still some bugs hidden in abapGit 😄

**Comment by larshp** [comment]
2 more missing:

- ZBOOK_AREAV
- ZBOOK_HISTORY

**Comment by tricktresor** [comment]
added.
Thanks, Lars!!

**Comment by abapkochbuch** [comment]
I created a kind of vicious circle:
```
SHLP ZBOOK_TICKET was not activated
TABL ZBOOK_TICKET is not a database table

TABL ZBOOK_TICKET was not activated
Search field ZBOOK_TICKET-TIKNR of ssearch help interface: SHLP ZBOOK_TICKET not active.

```
Even SAP does not get it activated in mass activation... :(

Also added some missing objects.

It's running now on my NPL. With lots of debugging, activation although errors exist and manual activations... *puh*

@se38 maybe you would like to try again some time...?

**Comment by se38** [comment]
Beside some problems with the "Original Language" and a syntax error there are no further issures. Good work (wasn't able to test all programs yet, of course).

**Comment by abapkochbuch** [comment]
Thanks for testing and feedback, @se38 Uwe!
